# Generated by Django 4.2.19 on 2025-03-16 21:32

import cla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[cla.models.ends_with_validator])),
                ('is_librarian', models.BooleanField(default=False)),
            ],
        ),
    ]
