# Generated by Django 4.2.19 on 2025-02-22 18:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarianItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('in_circulation', 'In Circulation'), ('out_of_stock', 'Out of Stock'), ('being_repaired', 'Being Repaired')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='LibrarianItems',
        ),
    ]
