# Generated by Django 4.2.19 on 2025-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0002_librarianitem_delete_librarianitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianitem',
            name='status',
            field=models.CharField(choices=[('in_circulation', 'In Circulation'), ('checked_in', 'Checked In'), ('out_of_stock', 'Out of Stock'), ('being_repaired', 'Being Repaired')], max_length=50),
        ),
    ]
