# Generated by Django 4.2.19 on 2025-03-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0003_alter_librarianitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarianitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
