# Generated by Django 4.2.19 on 2025-03-16 03:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0005_patronprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatronProfile',
            new_name='Profile',
        ),
    ]
