# Generated by Django 4.2.19 on 2025-03-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0006_rename_patronprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
