# Generated by Django 4.2.19 on 2025-03-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
