# Generated by Django 4.2.19 on 2025-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boardgame_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
