# Generated by Django 4.2.19 on 2025-03-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0010_alter_librarianitem_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianitem',
            name='image',
            field=models.ImageField(blank=True, default='default_boardgame.jpg', null=True, upload_to='boardgame_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
