# Generated by Django 4.2.19 on 2025-03-24 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0011_alter_librarianitem_image_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_private', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, null=True, related_name='collections', to='librarians.librarianitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('visible_to', models.ManyToManyField(blank=True, null=True, related_name='visible_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
