# Generated by Django 4.2.19 on 2025-03-24 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0012_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collections', to='librarians.librarianitem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
