# Generated by Django 4.2.19 on 2025-03-25 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0014_librarianitem_owner_alter_collection_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
