# Generated by Django 4.2.19 on 2025-04-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0016_review'),
        ('librarians', '0018_notification'),
    ]

    operations = [
    ]
