# Generated by Django 4.2.19 on 2025-04-11 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0019_merge_0016_review_0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarianitem',
            name='borrowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarianitem',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='librarianitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarianitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
