# Generated by Django 4.2.19 on 2025-04-12 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0020_librarianitem_borrowed_at_librarianitem_borrower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('not_received', 'Not Received')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='librarians.librarianitem')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
