# Generated by Django 4.2.19 on 2025-04-19 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarians', '0022_accountupgraderequest'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collectionaccessrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='itemaccessrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='itemreturnrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='librarianitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='librarianitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('in_repair', 'In Repair')], max_length=50),
        ),
        migrations.CreateModel(
            name='AccountUpgradeRequestRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='librarians.accountupgraderequest')),
            ],
            options={
                'unique_together': {('request', 'librarian')},
            },
        ),
    ]
