# Generated by Django 4.2.19 on 2025-04-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0023_collectionaccessrequest_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarianitem',
            name='image',
        ),
        migrations.CreateModel(
            name='LibrarianItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_boardgame.jpg', null=True, upload_to='boardgame_pics')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='librarians.librarianitem')),
            ],
        ),
    ]
