# Generated by Django 4.2.19 on 2025-04-26 16:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('librarians', '0025_alter_librarianitemimage_image'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='collectionaccessrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='itemaccessrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='itemreturnrequest',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_tagged_items', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='librarianitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='librarians.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
